CreateRegion("Menu")
CreateRegion("Brinstar Start")
CreateRegion("Brinstar Main")
CreateRegion("Brinstar Top")
CreateRegion("Brinstar Past Hives")
CreateRegion("Kraid Main")
CreateRegion("Kraid Acid Worm Area")
CreateRegion("Kraid Left Shaft")
CreateRegion("Kraid Bottom")
CreateRegion("Norfair Main")
CreateRegion("Norfair Right Shaft")
CreateRegion("Norfair Upper Right Shaft")
CreateRegion("Norfair Behind Ice Beam")
CreateRegion("Norfair Under Brinstar Elevator")
CreateRegion("Norfair Lower Right Shaft")
CreateRegion("Lower Norfair")
CreateRegion("Norfair Screw Attack Area")
CreateRegion("Norfair Behind Super Door")
CreateRegion("Norfair Bottom")
CreateRegion("Ridley Main")
CreateRegion("Ridley Left Shaft")
CreateRegion("Ridley SW Puzzle")
CreateRegion("Ridley Right Shaft")
CreateRegion("Ridley Speed Puzzles")
CreateRegion("Central Ridley")
CreateRegion("Ridley Room")
CreateRegion("Tourian")
CreateRegion("Crateria")
CreateRegion("Upper Crateria")
CreateRegion("Chozodia Ruins")
CreateRegion("Chozodia Ruins Test Area")
CreateRegion("Chozodia Glass Tube")
CreateRegion("Chozodia Under Tube")
CreateRegion("Chozodia Mothership Central")
CreateRegion("Chozodia Mothership Lower")
CreateRegion("Chozodia Mothership Upper")
CreateRegion("Chozodia Deep Mothership")
CreateRegion("Chozodia Mothership Cockpit")
CreateRegion("Chozodia Original Power Bomb Room")
CreateRegion("Chozodia Mecha Ridley Hallway")
CreateRegion("Mission Accomplished!")

ConnectRegions("Game Start", "Menu", "Brinstar Start")
ConnectRegions("Brinstar Start -> Main Shaft", "Brinstar Start", "Brinstar Main", MorphBall)
ConnectRegions("Brinstar Main -> Brinstar Top", "Brinstar Main", "Brinstar Top", brinstar_main_to_brinstar_top())
ConnectRegions("Brinstar Main -> Past Hives", "Brinstar Main", "Brinstar Past Hives", brinstar_past_hives())
ConnectRegions("Brinstar Past Hives -> Top", "Brinstar Past Hives", "Brinstar Top", brinstar_pasthives_to_brinstar_top())
ConnectRegions("Brinstar Top -> Past Hives", "Brinstar Top", "Brinstar Past Hives", CanEnterMediumMorphTunnel)
ConnectRegions("Brinstar -> Kraid Elevator", "Brinstar Start", "Kraid Main", CanSingleBombBlock)
ConnectRegions("Brinstar -> Norfair Elevator", "Brinstar Main", "Norfair Main", CanBombTunnelBlock)
ConnectRegions("Brinstar -> Tourian Elevator", "Brinstar Main", "Tourian", All(MorphBall, KraidBoss, RidleyBoss))
ConnectRegions("Brinstar -> Crateria Ballcannon", "Brinstar Start", "Upper Crateria", brinstar_crateria_ballcannon())
ConnectRegions("Kraid Main -> Acid Worm Area", "Kraid Main", "Kraid Acid Worm Area", kraid_upper_right())
ConnectRegions("Kraid Main -> Left Shaft", "Kraid Main", "Kraid Left Shaft", kraid_left_shaft_access())
ConnectRegions("Kraid Left Shaft -> Bottom", "Kraid Left Shaft", "Kraid Bottom", kraid_left_shaft_to_bottom())
ConnectRegions("Kraid -> Lower Norfair Shortcut", "Kraid Bottom", "Lower Norfair", kraid_bottom_to_lower_norfair())
ConnectRegions("Norfair -> Crateria Elevator", "Norfair Main", "Crateria", norfair_main_to_crateria())
ConnectRegions("Norfair Elevator -> Right Shaft", "Norfair Main", "Norfair Right Shaft", norfair_right_shaft_access())
ConnectRegions("Norfair Right Shaft -> Upper", "Norfair Right Shaft", "Norfair Upper Right Shaft", norfair_upper_right_shaft())
ConnectRegions("Norfair Right Shaft -> Under Elevator", "Norfair Right Shaft", "Norfair Under Brinstar Elevator", norfair_shaft_to_under_elevator())
ConnectRegions("Norfair Upper Right -> Behind Ice Beam", "Norfair Upper Right Shaft", "Norfair Behind Ice Beam", norfair_behind_ice_beam())
ConnectRegions("Norfair Ridley Shortcut", "Norfair Behind Ice Beam", "Norfair Bottom", norfair_behind_ice_to_bottom())
ConnectRegions("Norfair Right Shaft -> Lower Shaft", "Norfair Under Brinstar Elevator", "Norfair Lower Right Shaft", norfair_lower_right_shaft())
ConnectRegions("Norfair Lower Shaft -> Under Brinstar Elevator", "Norfair Lower Right Shaft", "Norfair Under Brinstar Elevator", norfair_lower_shaft_to_under_elevator())
ConnectRegions("Norfair Right Shaft -> Lower Norfair", "Norfair Lower Right Shaft", "Lower Norfair", norfair_lower_right_shaft_to_lower_norfair())
ConnectRegions("Lower Norfair -> Screw Attack", "Lower Norfair", "Norfair Screw Attack Area", lower_norfair_to_screwattack())
ConnectRegions("Lower Norfair -> Behind Super Missile Door", "Lower Norfair", "Norfair Behind Super Door", lower_norfair_to_spaceboost_room())
ConnectRegions("Lower Norfair -> Kraid", "Lower Norfair", "Kraid Bottom", lower_norfair_to_kraid())
ConnectRegions("Lower Norfair -> Bottom", "Lower Norfair", "Norfair Bottom", lower_norfair_to_bottom_norfair())
ConnectRegions("Lower Norfair -> Lower Right Shaft", "Lower Norfair", "Norfair Lower Right Shaft", lower_norfair_to_lower_right_shaft())
ConnectRegions("Norfair Bottom -> Norfair Lower Right Shaft", "Norfair Bottom", "Norfair Lower Right Shaft", bottom_norfair_to_lower_shaft())
ConnectRegions("Norfair -> Ridley Elevator", "Norfair Bottom", "Ridley Main", bottom_norfair_to_ridley())
ConnectRegions("Norfair Bottom -> Screw Attack", "Norfair Bottom", "Norfair Screw Attack Area", bottom_norfair_to_screw())
ConnectRegions("Norfair Screw Attack -> Lower Norfair", "Norfair Screw Attack Area", "Lower Norfair", screw_to_lower_norfair())
ConnectRegions("Ridley Elevator -> Left Shaft", "Ridley Main", "Ridley Left Shaft", ridley_main_to_left_shaft())
ConnectRegions("Ridley Elevator -> Right Shaft Shortcut", "Ridley Main", "Ridley Right Shaft", ridley_main_to_right_shaft())
ConnectRegions("Ridley Left Shaft -> SW Puzzle", "Ridley Left Shaft", "Ridley SW Puzzle", ridley_left_shaft_to_sw_puzzle())
ConnectRegions("Ridley Left Shaft -> Right Shaft", "Ridley Left Shaft", "Ridley Right Shaft")
ConnectRegions("Ridley Right Shaft -> Left Shaft", "Ridley Right Shaft", "Ridley Left Shaft", ridley_right_shaft_to_left_shaft())
ConnectRegions("Ridley Right Shaft -> Speed Puzzles", "Ridley Right Shaft", "Ridley Speed Puzzles", ridley_speed_puzzles_access())
ConnectRegions("Ridley Right Shaft -> Central", "Ridley Right Shaft", "Central Ridley", ridley_right_shaft_to_central())
ConnectRegions("Ridley Right Shaft -> SW Puzzle", "Ridley Right Shaft", "Ridley SW Puzzle", ridley_left_shaft_to_sw_puzzle())
ConnectRegions("Ridley Central -> Ridley's Room", "Central Ridley", "Ridley Room", ridley_central_to_ridley_room())
ConnectRegions("Tourian Escape -> Chozodia", "Tourian", "Chozodia Ruins Test Area", tourian_to_chozodia())
ConnectRegions("Crateria -> Upper", "Crateria", "Upper Crateria", crateria_main_to_crateria_upper())
ConnectRegions("Crateria -> Chozodia Lower Door", "Crateria", "Chozodia Under Tube", crateria_to_under_tube())
ConnectRegions("Crateria -> Chozodia Upper Door", "Upper Crateria", "Chozodia Ruins", crateria_upper_to_chozo_ruins())
ConnectRegions("Chozo Ruins -> Chozo Ruins Test", "Chozodia Ruins", "Chozodia Ruins Test Area", chozo_ruins_to_ruins_test())
ConnectRegions("Chozo Ruins Test -> Chozo Ruins", "Chozodia Ruins Test Area", "Chozodia Ruins", ChozoGhostBoss)
ConnectRegions("Chozo Ruins -> Glass Tube", "Chozodia Ruins", "Chozodia Glass Tube", chozo_ruins_to_chozodia_tube())
ConnectRegions("Chozodia Under Tube -> Crateria", "Chozodia Under Tube", "Crateria", under_tube_to_crateria())
ConnectRegions("Chozodia Under Tube -> Glass Tube", "Chozodia Under Tube", "Chozodia Glass Tube", under_tube_to_tube())
ConnectRegions("Chozodia Glass Tube -> Under Tube", "Chozodia Glass Tube", "Chozodia Under Tube", tube_to_under_tube())
ConnectRegions("Chozodia Glass Tube -> Chozo Ruins", "Chozodia Glass Tube", "Chozodia Ruins", chozodia_tube_to_chozo_ruins())
ConnectRegions("Chozozia Glass Tube -> Mothership Central", "Chozodia Glass Tube", "Chozodia Mothership Central", chozodia_tube_to_mothership_central())
ConnectRegions("Chozodia Central Mothership -> Lower Mothership", "Chozodia Mothership Central", "Chozodia Mothership Lower", mothership_central_to_lower())
ConnectRegions("Chozodia Central Mothership -> Upper Mothership", "Chozodia Mothership Central", "Chozodia Mothership Upper", mothership_central_to_upper())
ConnectRegions("Chozodia Lower Mothership -> Upper Mothership", "Chozodia Mothership Lower", "Chozodia Mothership Upper", mothership_lower_to_upper())
ConnectRegions("Chozodia Upper Mothership -> Lower Mothership", "Chozodia Mothership Upper",
            "Chozodia Mothership Lower", mothership_upper_to_lower())
ConnectRegions("Chozodia Upper Mothership -> Deep Mothership", "Chozodia Mothership Upper",
            "Chozodia Deep Mothership", mothership_upper_to_deep_mothership())
ConnectRegions("Chozodia Deep Mothership -> Cockpit", "Chozodia Deep Mothership",
            "Chozodia Mothership Cockpit", deep_mothership_to_cockpit())
ConnectRegions("Chozodia Cockpit -> Original PB", "Chozodia Mothership Cockpit", "Chozodia Original Power Bomb Room", cockpit_to_original_pb())
ConnectRegions("Chozodia Cockpit -> Mecha Ridley", "Chozodia Mothership Cockpit", "Chozodia Mecha Ridley Hallway", cockpit_to_mecha_ridley())
